web:
  build: .
  ports:
    - "80:8080"
  environment:
    NODE_ENV: production
  links:
    - api
api:
  build: ./api
  ports:
    - "8888:8888"
  environment:
    NODE_ENV: production
  links:
    - mongo
mongo:
  image: mongo
  ports:
    - "27017:27017"
